### PR TITLE
kk -  school table and school utils component in addition to the storybook.

### LINKED ISSUE #69: FRONTEND: Create a table for schools api
# FRONTEND: Create a table for schools api #69 
Requirements
- [x] Create the table
- [x] Create Utils File for Schools table
- [x] Create testing for both Utils and Schools table

### PR DESCRIPTION
**Pull request by vcnardi524**
Victor Nardi
 - Here we added School table in addition to its testing.
 - The school table has been implemented as storybook below shows. The link to the story book is also attached below.
 - Includes a Utils file for school. 
 - added the following import statement "import edu.ucsb.cs156.organic.errors.EntityNotFoundException;" for proper 100% mutation coverage.

Storybook - https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-1/prs/68/storybook/?path=/story/components-school-schooltable--empty
Screenshot 2024-03-17 at 2 09 16 AM

deployment link - https://organic-shashank790-dev.dokku-09.cs.ucsb.edu/

Closes #69

### CODE REVIEW

**Review by sanilkatula — DISMISSED** [review]
LGTM!

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by sanilkatula — DISMISSED** [review]
LGTM

**Review by whuang602 — CHANGES_REQUESTED** [review]
Can you please provide more explanation as to what this accomplishes, either with words or images. As well as storybook or deployment links depending on what you specifically implemented.

**Review by sanilkatula — APPROVED** [review]

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — APPROVED** [review]

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — APPROVED** [review]

**Review by sanilkatula — APPROVED** [review]

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
