### PR TITLE
kk - resolved [BUG]: Last Online in User Profile Defaults to Wrong Date

### LINKED ISSUE #6: BUG: Last Online in User Profile Defaults to Wrong Date
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Under the user profile page in the Organic web app, the Last Online value is always set to be 1/20/1970. (5)

(Note: 1/1/1970 is the unix epoch)

### Expected Behavior

The value should be updated to "Online now" or something more appropriate. 

### Current / Observed Behavior

Currently, the Last Online value does not accurately reflect what the user's activity status is.

### Steps to Reproduce

1. Login with GitHub OAuth
2. Click the top right "Welcome, user" text
3. The topmost table indicates the wrong date for "Last Online"
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by sanilkatula**
Added timestamp by removing instant.

Screenshot 2024-03-13 at 7 06 27 PM

Screenshot 2024-03-07 at 10 34 48 AM

deployment link - https://sanil-toggle-pop-up.dokku-09.cs.ucsb.edu/

closes #6

### CODE REVIEW

**Comment by phillylim** [comment]
Looks good to me; it does the necessary changes to add date time updating correctly under profiles.

**Review by phillylim — APPROVED** [review]
Looks good to me, does the necessary changes to correctly update the date time in profile pages

**Review by shashank790 — COMMENTED** [review]
Looks good to me.

**Review by shashank790 — DISMISSED** [review]

**Review by phillylim — DISMISSED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by whuang602 — CHANGES_REQUESTED** [review]
What does this PR accomplish? I do not see any changes except for the location movement of newlines and curly basis

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by KushagraKanaujia — APPROVED** [review]

**Review by KushagraKanaujia — DISMISSED** [review]

**Review by shashank790 — APPROVED** [review]
LGTM

**Comment by sanilkatula** [comment]
Made changes as per your request. Hope it works.

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
