### PR TITLE
sk - added [Feature] join for normal user

### LINKED ISSUE #9: FEATURE: [Frontend] Normal User Join Action
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

normal user (student)

### I can...

click on a join button

### So that...

I can join the course's Github Organization

### Discussion

This issue assumes that the student user can now access the courses page. Create a frontend button that the normal user can click. (5)

### Acceptance Criteria

- [x] Normal user can see a "Join" (or similarly named) button in the courses table
- [x] Normal user can actually click on the button (no backend for now)

### Implementation Todos

Frontend:
- [x] Normal user instead of seeing edit or delete, can see a join button
- [x] Join button can be clicked but does not do anything (for now)

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by sanilkatula**
I added the join button for users to see.
Admin and Instructors can not see the join button.
Mutation is 100% for both frontend and backend.

Screenshot 2024-02-29 at 9 30 21 PM

deployment link - https://sanil-toggle-pop-up.dokku-09.cs.ucsb.edu/

closes #9

### CODE REVIEW

**Review by phillylim — COMMENTED** [review]
Perfect, this builds on the last feature, and sets up for backend functionality to join courses.

**Review by shashank790 — COMMENTED** [review]
Looks good to me.

**Review by shashank790 — DISMISSED** [review]

**Review by shashank790 — DISMISSED** [review]

**Review by jenil-prajapati — DISMISSED** [review]
looks good to me

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by KushagraKanaujia — DISMISSED** [review]

**Review by KushagraKanaujia — DISMISSED** [review]

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by shashank790 — APPROVED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by whuang602 — DISMISSED** [review]
LGTM

**Review by jenil-prajapati — APPROVED** [review]
good to go!

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
