### PR TITLE
sk - added [FEATURE]: Instructors can create, edit and delete courses

### LINKED ISSUE #1: FEATURE: Instructors can create courses
# Dependencies

This issue cannot be started until after there has been enough progress on the Epic for creating the Instructor role so that ROLE_INSTRUCTOR exists in the database.

# User Story

* As an instructor
* I can create a new course
* So that I don't have to rely on admins to create courses

### Discussion

This issue cannot be started until after there has been enough progress on the Epic for creating the Instructor role so that ROLE_INSTRUCTOR exists in the database.

Currently, only Admins can create courses.

In this issue, we'll modify that so that Instructors can also create courses.

Once an instructor creates a course, they will be automatically a staff member for that course so that will be the way in which we determine whether or not they have permissions to do course management features.  So only the creation of the course is affected.

For now, we'll assume that only admins can delete a course.

### Acceptance Criteria

- [x] Anyone with ROLE_ADMIN or ROLE_INSTRUCTOR can create a course.
- [x] The frontend access to creating a course only shows up for users with  ROLE_ADMIN or ROLE_INSTRUCTOR

### PR DESCRIPTION
**Pull request by sanilkatula**
100% mutation testing.
Made sure that instructors and admins can create courses.
Only Admins and Instructors can see the create course button.

SanShock is user with instructor privileges!
Screenshot 2024-03-11 at 6 52 19 PM

They can see the create button 
Screenshot 2024-03-11 at 6 52 35 PM

They can create a course too
Screenshot 2024-03-11 at 6 53 04 PM

They also have the privilages to edit and delete the course
Screenshot 2024-03-11 at 7 00 03 PM

closes #1

### CODE REVIEW

**Review by shashank790 — DISMISSED** [review]
Looks good to me, edited files are in accordance with those stated in title.

**Review by shashank790 — COMMENTED** [review]
Look good to me.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Please include image(s) and deployment link

**Comment by sanilkatula** [comment]
Deployment link -  https://organic-sanil-dev.dokku-09.cs.ucsb.edu

**Review by whuang602 — CHANGES_REQUESTED** [review]
Everything looks great. But it would be great if you can modify Interceptors to all be lowercase i. Not your fault, it just slipped through the crack.

**Comment by sanilkatula** [comment]
did that.
but any particular reason for that? because on local device it gave compilation error.

**Comment by jenil-prajapati** [comment]
Looks good to me!

**Comment by jenil-prajapati** [comment]
looks good to me!

**Review by jenil-prajapati — DISMISSED** [review]

**Comment by whuang602** [comment]
Note that you also have to change the directory name to lowercase.

**Review by jenil-prajapati — DISMISSED** [review]

**Comment by sanilkatula** [comment]
done :)

**Review by phillylim — DISMISSED** [review]
LGTM

**Review by shashank790 — APPROVED** [review]
Looks good to me

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
