### PR TITLE
Jenil school get one and get all

### LINKED ISSUE #15: FEATURE: GET /api/schools/all
Acceptance Criteria:

- [ ] When testing the deployed application and in swagger, the /api/schools/all displays all of the entries. 
- [ ] An API should call should return the contents of any mock resources (backend tests)

Implementation Todos:

- [ ] Edit the /api/schools/all endpoint to do return all of the contents of the corresponding table
- [ ] Add test cases testing for each of the fields to make sure with mock resources 
- [ ] Ensure adequate test and mutation coverage

### PR DESCRIPTION
**Pull request by jenil-prajapati**
closes #15 and #17, 
- this implements GET section of the school api
- it has both **get all** and **get by one specific id** for which all the authorization tests such as logged in user, existence of id etc all pass

deployment link - https://sanil-toggle-pop-up.dokku-09.cs.ucsb.edu/

Screenshot 2024-03-12 at 6 03 37 PM
Screenshot 2024-03-14 at 5 39 46 PM

### CODE REVIEW

**Comment by jenil-prajapati** [comment]
closes #15 and #17 (GET)

**Comment by sanilkatula** [comment]
can you explain in detail what you did?

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by sanilkatula — APPROVED** [review]

**Comment by sanilkatula** [comment]
LGTM - you implemented two api's here. great.

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — APPROVED** [review]

**Review by whuang602 — APPROVED** [review]
LGTM

**Review by vcnardi524 — COMMENTED** [review]
Looks good now, passed all the tests!

**Review by vcnardi524 — COMMENTED** [review]
Officially final review, everything check out now

**Pull request merged**
