### PR TITLE
PL - Bug fix footer

### LINKED ISSUE #5: BUG: It's a Typo in the Footer
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

There is a typo in the footer of the organic web app. (5)

### Expected Behavior

It's vs its, completely different meaning. "It's" = it is and "its" mean belonging to it.

The footer should state "Its purpose..." as opposed to "It's purpose..."

### Current / Observed Behavior

Currently the sentence says "It's purpose" which means It is purpose as opposed to purpose of it.

### Steps to Reproduce

1. Bottom of the front page
2.
3.
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by phillylim**
If applied, it will add the changes to the footer to reflect the correct information. This also has to update the corresponding test cases to ensure 100% test and mutation coverage. There is now added adversarial testing to ensure that the corresponding grammatical error does not appear again in the future by accident.
Acceptance Criteria:
image

https://organic-phillylim-dev.dokku-09.cs.ucsb.edu/
Closes #5

### CODE REVIEW

**Review by sanilkatula — DISMISSED** [review]
great. good to go

**Review by shashank790 — DISMISSED** [review]
Looks good to me.

**Review by whuang602 — APPROVED** [review]
LGTM

**Comment by sanilkatula** [comment]
LGTM

**Review by sanilkatula — APPROVED** [review]
LGTM

**Pull request merged**
