### PR TITLE
PL - Icon bug fix

### LINKED ISSUE #8: BUG: Inaccurate Icon
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Currently, the icon for project organic is a cow (a happy one at that). This is not accurate and does not properly represent the web application.  (5)

### Expected Behavior

The icon of the app should adequately and properly represent what the app does and what it represents.

### Current / Observed Behavior

The current icon is a cow. However the codename of the application isn't anything related to cows.

### Steps to Reproduce

1. Look at your tab at the top of the screen next to "Organic"
2.
3.
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by phillylim**
If applied, it will updat the corresponding favicon.ico to be something that isn't a cow, and something that resembles `organic` a bit better.

Acceptance Criteria (icon in local host):
image

New Icon:
organic_project_icon_512

https://organic-phillylim-dev.dokku-09.cs.ucsb.edu/
Closes #8

### CODE REVIEW

**Review by shashank790 — DISMISSED** [review]
Looks good to me, edited files are in accordance with those stated in title.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Please double check and ensure this is a copyright free image. It would be greatly appreciated if you can demonstrate where this image was sourced from and/or if you created it yourself, please include that you grant us all necessary rights to use the image for the project.

**Comment by phillylim** [comment]
I own the image rights to this image, as I used an AI image generator where in the private policy it says the image is mine.
I grant all necessary rights to use this image for the project - Philly Lim

**Review by whuang602 — CHANGES_REQUESTED** [review]
Could you send a link to the page that says that you own the rights to the image generated?

**Review by sanilkatula — DISMISSED** [review]
LGTM

**Comment by phillylim** [comment]
https://help.openai.com/en/articles/6425277-can-i-sell-images-i-create-with-dall-e

https://openai.com/policies/usage-policies

https://openai.com/policies/terms-of-use

**Review by sanilkatula — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
