### PR TITLE
Jenil add entity and repository class for schools table

### LINKED ISSUE #12: FEATURE: [Backend] Add entity and repository class for schools table
Acceptance criteria:

- [ ] entity class is made for schools table
- [ ] repository class is made for schools table

Implementation Todos

- [ ]  Add the respective class files
- [ ] Add test cases for adequate test coverage and mutation coverage

### PR DESCRIPTION
**Pull request by jenil-prajapati**
closes #12

### CODE REVIEW

**Comment by sanilkatula** [comment]
which issue does it closes?

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Review by sanilkatula — DISMISSED** [review]
LGTM

**Review by whuang602 — CHANGES_REQUESTED** [review]
Actually, can you explain more what was added in this PR?

**Comment by jenil-prajapati** [comment]
> Actually, can you explain more what was added in this PR?

I added repo and entities for school since it needed some initial tests to run for checks to pass i put schooltests as well.

**Comment by sanilkatula** [comment]
Both FIXME's are fixed!

**Review by sanilkatula — APPROVED** [review]

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
