### PR TITLE
Victor school delete dev

### LINKED ISSUE #21: FEATURE: DELETE /api/schools?id=123
Acceptance Criteria:

- [ ] When testing the deployed application, given that the table that is populated and the id of a row, it successfully deletes the corresponding row
- [ ] This should also be successfully deleted within the swagger. 

Implementation Todos:

- [ ] add the DELETE /api/schools?id=XXX endpoint with corresponding controllers and service files
- [ ] Add test cases testing for each of the fields to make sure it successfully deletes mock resources.
- [ ] Ensure adequate test and mutation coverage

### PR DESCRIPTION
**Pull request by vcnardi524**
Victor Nardi - implemented DELETE part of School controller. 
- This is a part of the backend functionality. This also includes the liquibase file for schools api.
- This takes in abbrev as a string based id
- deployment link - https://organic-sanil-dev.dokku-09.cs.ucsb.edu/

Screenshot 2024-03-12 at 7 20 15 PM

Closes #21

### CODE REVIEW

**Review by sanilkatula — DISMISSED** [review]
Looks Awesome

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by shashank790 — APPROVED** [review]
LGTM

**Comment by sanilkatula** [comment]
deployment link - https://organic-sanil-dev.dokku-09.cs.ucsb.edu/

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by sanilkatula — APPROVED** [review]

**Review by sanilkatula — APPROVED** [review]

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
