### PR TITLE
sb - [Feature] added total courses counter to course table

### LINKED ISSUE #63: [Feature] - Course table displays a counter for the total number of courses that it is displaying

### PR DESCRIPTION
**Pull request by shashank790**
Closes #63 

If applied, you are now able to see the total number of courses that are within the table, as below:

deployment link  - https://organic-sanil-dev.dokku-09.cs.ucsb.edu/

Screenshot 2024-03-06 at 12 37 43 PM

### CODE REVIEW

**Review by sanilkatula — APPROVED** [review]
LGTM

**Review by sanilkatula — APPROVED** [review]
LGTM

**Review by phillylim — APPROVED** [review]
LGTM

**Review by whuang602 — COMMENTED** [review]
This seems like a somewhat random and unwarranted feature. I don't see how this is necessary for the application. PR itself looks good, just uncertain as to what it serves to accomplish. Will check with other staff tomorrow and confirm whether this should be merged.

**Comment by sanilkatula** [comment]
I think this feature is definitely a great one. Even on our gold we have a course counter. So I think this should be merged.

And even the course deletes function. An admin should know how many courses have been deleted or created.

I know what a better feature would be that. Admin can even see the deleted courses. That would be insane. But this is also a start.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Would be great if you can include a deployment link

**Comment by sanilkatula** [comment]
deployment link - https://organic-sanil-dev.dokku-09.cs.ucsb.edu/

**Review by sanilkatula — APPROVED** [review]

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
