### PR TITLE
PL- [Feature] User view course

### LINKED ISSUE #7: FEATURE: Normal User Can See Courses
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

normal user (student)

### I can...

see the course list

### So that...

I can join the course's GitHub organization

### Discussion

Currently, as a normal user (student) you are unable to do anything. In fact, the web application does not show a normal user anything at all. (10)
Future work (EDIT FROM OUR TEAM AND TALKING TO TAs):
This issue is actually more involved. There needs to be backend changes. As of right now, the get/all feature only gets everything either if you are a ADMIN or staffed. There needs to be a distinguishing of the two. This is because whoever made changes to the API basically made the API endpoint /all combine logic for getting everything and getting everything for staff (which doesn't have the necessarily be ADMIN or INSTRUCTOR, ex TA). The cleanest solution would be the separation of these API endpoints; however, this would mean any frontend changes would need to be modified. Proposing this be changed to an epic (20 points) due to the complexity of the issue due to technical debt. This can be a task assigned for future work. 

### Acceptance Criteria

- [x] [Frontend] Normal users can access the course page
- [x] [Frontend] Normal users cannot see any course unless they are enrolled (not implemented)
### Future work
- [ ] [Backend] Need a lot of changes, potentially a new table

### Implementation Todos

Frontend:
- [x] Add viewing and access privileges to ROLE_USER
- [x] DO NOT allow them to create, edit, or delete (they are not an admin or instructor! They shouldn't even see the buttons) 

Testing:
- [x] Front end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by phillylim**
If applied, it will allow users to now view courses that they are staffed in, and it allows the navigation bar to show this path. Future work to see ALL courses will require future work
Acceptance Criteria:

image

https://organic-phillylim-dev.dokku-09.cs.ucsb.edu/

Closes #7

### CODE REVIEW

**Comment by sanilkatula** [comment]
fails some checks. lets fix those and make another pull request.

**Review by sanilkatula — DISMISSED** [review]
wonderful. I like the new changes. I am gonna approve.

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — DISMISSED** [review]
LGTM

**Review by whuang602 — DISMISSED** [review]
LGTM

**Review by whuang602 — CHANGES_REQUESTED** [review]
Merge main caused some test issues, will merge after fix. Points already awarded. (10)

**Review by sanilkatula — APPROVED** [review]
LGTM

**Review by vcnardi524 — APPROVED** [review]
Looks good

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
