### PR TITLE
Victor school post dev

### LINKED ISSUE #14: FEATURE: POST /api/schools school (does backend validation of fields at least in terms of required/optional)
Acceptance Criteria:

- [ ] When testing the deployed application, it rejects invalid inputs according to a regex or incorrect format on the backend.
- [ ] There should be an error thrown if invalid; the code is tentative but might be 4XX

Implementation Todos:

- [ ] Edit the /api/schools endpoint to do this validation of fields
- [ ] Add test cases testing for each of the fields to make sure it does the validation correctly
- [ ] Ensure adequate test and mutation coverage

### PR DESCRIPTION
**Pull request by vcnardi524**
Victor Nardi - this finishes the POST part of the schools controller in the backend section. Test cases are included. 
- Below you can see an image of the swagger interface. 

- The abbrev has to be all lowercase.

 - The format of termDescription is set by the value of termRegex. Example if  termRegex =  "[WSMF]\\d\\d" then termDescription must look like F24 or something similar. If these conditions aren't met an dynamically implemented illegal argument error is thrown.

deployment link - https://sanil-toggle-pop-up.dokku-09.cs.ucsb.edu/

Closes #14 

Screenshot 2024-03-12 at 7 13 36 PM

### CODE REVIEW

**Review by sanilkatula — DISMISSED** [review]
LGTM! 
great work vicktor

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by sanilkatula — APPROVED** [review]
LGTM

**Comment by sanilkatula** [comment]
is it 15 points now?

**Review by whuang602 — CHANGES_REQUESTED** [review]
LGTM, but it would be nice if you can provide a deployment link (or at least for swagger) so I can test it. Once it's tested it will be merged.

**Comment by sanilkatula** [comment]
deployment link - https://sanil-toggle-pop-up.dokku-09.cs.ucsb.edu/

**Review by shashank790 — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
