### PR TITLE
sk - [Feature] added staff button. in addition to a table component, fixtures and storybook.

### LINKED ISSUE #24: [FEATURE] - There is a button on the course table labelled "Staff" that navigates to the staff page at the frontend url `/courses/{courseId}/staff`.

### LINKED ISSUE #25: There is a table component to list staff members, and fixures that match the `GET /api/course/staff/all?courseId=123` endpoint

### PR DESCRIPTION
**Pull request by sanilkatula**
Staff Button:

Screenshot 2024-03-05 at 10 42 56 AM

Storybook Representation for fixtures:

Screenshot 2024-03-11 at 3 54 22 PM

link to story book - https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-1/prs/58/storybook/?path=/story/components-staff-stafftable--empty

closes #24 
closes #25

Staff page currently serves as a placeholder and will be replaced by the actual staff page after future PRs.

### CODE REVIEW

**Review by shashank790 — DISMISSED** [review]
Looks good to me, closes the issues listed.

**Review by jenil-prajapati — DISMISSED** [review]
good to go

**Comment by sanilkatula** [comment]
I am not sure. But wasn't Staff table component and fixture are 15 points? However in my PR I also add the staff button.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Looks good, but instead of commenting out code, just delete them. Also add everything you implemented to the PR description, also adding a link would be nice too.

**Comment by sanilkatula** [comment]
deployment link -  https://sanil-toggle-pop-up.dokku-09.cs.ucsb.edu

this deployment is up to date with the main and also contains the deployment for this PR.

**Review by shashank790 — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
