### PR TITLE
Victor school put dev

### LINKED ISSUE #20: FEATURE: PUT /api/schools?id=123
Acceptance Criteria:

- [ ] When testing the deployed application, given that the table that is populated and the id of a row, it successfully updates the corresponding row
- [ ] This should also be successfully updated within the swagger web page. 

Implementation Todos:

- [ ] add the PUT /api/schools?id=XXX endpoint with corresponding controllers and service files
- [ ] Add test cases testing for each of the fields to make sure it successfully updates mock resources.
- [ ] Ensure adequate test and mutation coverage

### PR DESCRIPTION
**Pull request by vcnardi524**
Victor Nardi - Fully implements PUT section of the schools API. All tests are passing. 
- Takes university domain name abbrev in the form of a string as input
- details can be input through the request body window
- deployment link - https://organic-phillylim-dev.dokku-09.cs.ucsb.edu/

Screenshot 2024-03-12 at 7 22 40 PM

Closes #20

### CODE REVIEW

**Review by sanilkatula — DISMISSED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by sanilkatula — APPROVED** [review]
LGTM

**Review by sanilkatula — DISMISSED** [review]
LGTM

**Comment by sanilkatula** [comment]
deployment link -  https://organic-phillylim-dev.dokku-09.cs.ucsb.edu

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — DISMISSED** [review]

**Review by sanilkatula — APPROVED** [review]

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
