### PR TITLE
sk - [Feature] gave the website a look over.

### PR DESCRIPTION
**Pull request by sanilkatula**
### Login Page

**Earlier**
Screenshot 2024-03-07 at 8 46 27 PM

**Now**
Screenshot 2024-03-07 at 8 47 15 PM

### Home Page

**Earlier**
Screenshot 2024-03-07 at 8 47 46 PM

**Now**
Screenshot 2024-03-07 at 8 48 17 PM

### Page not found

**Earlier**
Screenshot 2024-03-07 at 8 48 58 PM

**Now**
Screenshot 2024-03-07 at 8 49 20 PM

here, 
the search bar is a place holder and is a TODO. The home button takes the user to home. The course button would take the user to courses once merged with the main. Contact us and let us know are also a place holder.

### CODE REVIEW

**Review by jenil-prajapati — DISMISSED** [review]
looks good to me!

**Review by phillylim — DISMISSED** [review]
LGTM

**Review by jenil-prajapati — APPROVED** [review]
looks good to me!

**Review by whuang602 — APPROVED** [review]
Looking great!

**Pull request merged**
