### PR TITLE
PL - Feature Implementation: Admin popup confirmation

### LINKED ISSUE #2: FEATURE: Pop-ups for Admin Toggles
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

admin

### I can...

receive a pop-up when I try to toggle roles

### So that...

I can accurately decide whether I want to alter roles

### Discussion

Currently, admins can modify other users' roles with one click. This can be detrimental if it wasn't done intentionally, this can also potentially result in problems for other admins. A pop-up or confirmation request would be a great change that ensures security and user safety. (10)

### Acceptance Criteria

- [x] When an admin clicks on "toggle-admin" they get a pop up that asks them if they are sure they want to toggle admin role
- [x] When an admin clicks on "toggle-instructor" they get a pop up that asks them if they are sure they want to toggle instructor role

### Implementation Todos

Frontend:
- [x] Add a confirmation popup before the toggle backend is triggered (feel free to look up how to do this)

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by phillylim**
If applied, it will make the `admin/users` page employ protections to safeguard against toggling a user by accident. A pop up window will appear, and upon confirmation, an asynchronous call to the mutation will occur--if they do not confirm, no changes are made. 

Changed test cases to mock confirmation input, allowing for 100% test and mutation coverage. Added more comprehensive test cases to test for conditional rendering and branching.

Acceptance Criteria:
image

Clicking "OK":
image
Clicking "Cancel":
image

Deployment link: http://organic-phillylim-dev.dokku-09.cs.ucsb.edu/
Closes #2

### CODE REVIEW

**Review by shashank790 — DISMISSED** [review]
Looks good to me, edited files are in accordance with those stated in title.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Why are there so many changed files within this PR? Some changed files are unrelated. I can approve and merge this but it may result in less points.

**Comment by phillylim** [comment]
These are with my previous commits as well. I think for the least amount of changes, it would be ideal to review changes from the earliest PR to the latest PR.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Please include a deployment link

**Comment by phillylim** [comment]
http://organic-phillylim-dev.dokku-09.cs.ucsb.edu/

**Pull request closed without merging**
