### PR TITLE
sk - [Feature] developer can use unlimited colors for buttons 

### LINKED ISSUE #55: [Feature] - developer can use more colors for buttons
Acceptance criteria - 

- [x] developer can use any color they want for the button

### PR DESCRIPTION
**Pull request by sanilkatula**
I added the code such that now "ButtonColumn" can take in both variant and hexcode which gives the developer more colors to work with for buttons.

Like in the below image I have used green color for edit, earlier I was stuck with variants like; primary(blue), secondary(grey) and danger(red). Now we have unlimited options using hex codes.

Also added a condition that changes the text color to black if the background is getting light and changes the font back to white on dark backgrounds

deployment link - https://organic-sanil-dev.dokku-09.cs.ucsb.edu/

Screenshot 2024-03-01 at 12 11 58 PM

closes #55

### CODE REVIEW

**Review by phillylim — DISMISSED** [review]
excellent, this is a very well polished feature that allows for flexible customizability

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by KushagraKanaujia — DISMISSED** [review]
lgtm

**Review by shashank790 — DISMISSED** [review]
LGTM

**Review by whuang602 — CHANGES_REQUESTED** [review]
It would be great if you can change the interceptors imports and folder or else the code will likely break again.

**Comment by sanilkatula** [comment]
Resolved conflicts.
Fixed the bug.

**Review by jenil-prajapati — DISMISSED** [review]

**Review by whuang602 — DISMISSED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Review by shashank790 — APPROVED** [review]
LGTM

**Review by phillylim — APPROVED** [review]
This is an excellent feature which will help the visually impaired. This is amazing and well tested. The test cases have 100% unit and mutation coverage. The changes themselves follow good naming standards and coding practices. The cloud deployment shows the added changes. Great work!

**Comment by KushagraKanaujia** [comment]
looks good.

**Pull request merged**
